apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: portfolio
  source:
    repoURL: https://github.com/eswarmaganti/portfolio-website.git
    targetRevision: main
    path: chart/nginx
    helm:
      releaseName: portfolio-website
      valueFiles:
        - values.yaml
      parameters:
        - name: "image.tag"
          value: "4"
  syncPolicy:
    syncOptions:
      - CreteNamespace=true