apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.cert.name }}
spec:
  commonName: {{ .Values.cert.dnsNames }}
  dnsNames:
      - {{ .Values.cert.dnsNames }}
  secretName: {{ .Values.cert.secretName }}
  issuerRef:
      {{- with .Values.cert.issuerRef }}
      {{- toYaml . | nindent 4 }}
      {{- end }}