{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
  {{- include "nginx.labels" . | nindent 4}}
type: {{ .Values.secret.type }}
data:
  .dockerconfigjson: {{ .Values.secret.dockerConfigJSON }}
{{- end }}